# Generated by Django 6.0.5 on 2026-05-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profil',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='site',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
