# Generated by Django 6.0.5 on 2026-05-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_parametres_contact_ui_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='niveau_a_desc',
            field=models.TextField(blank=True, default='Maîtrisez les outils bureautiques essentiels utilisés dans tous les métiers.'),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_a_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_a_sous',
            field=models.CharField(blank=True, default='Débutant', max_length=100),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_a_titre',
            field=models.CharField(blank=True, default='Niveau A', max_length=100),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_b_desc',
            field=models.TextField(blank=True, default='Explorez le design graphique et créez des visuels professionnels percutants.'),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_b_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_b_sous',
            field=models.CharField(blank=True, default='Intermédiaire', max_length=100),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_b_titre',
            field=models.CharField(blank=True, default='Niveau B', max_length=100),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_c_desc',
            field=models.TextField(blank=True, default='Devenez développeur ou expert cybersécurité avec les technologies actuelles.'),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_c_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_c_sous',
            field=models.CharField(blank=True, default='Avancé', max_length=100),
        ),
        migrations.AddField(
            model_name='parametres',
            name='niveau_c_titre',
            field=models.CharField(blank=True, default='Niveau C', max_length=100),
        ),
    ]
