# Generated by Django 6.0.5 on 2026-05-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_inscription_unique_together_inscription_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificat',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificat',
            name='niveau',
            field=models.CharField(blank=True, choices=[('A', 'Niveau A'), ('B', 'Niveau B'), ('C', 'Niveau C')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats', to='api.formation'),
        ),
    ]
