# Generated by Django 6.0.5 on 2026-05-28 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_certificat_date_debut_certificat_date_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inscription',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='api.formation'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(condition=models.Q(('formation__isnull', False)), fields=('utilisateur', 'formation'), name='unique_inscription_formation'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(condition=models.Q(('formation__isnull', True)), fields=('utilisateur', 'niveau'), name='unique_inscription_niveau'),
        ),
    ]
