# Generated by Django 6.0.5 on 2026-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_inscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='lecons/fichiers/'),
        ),
    ]
