import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useLangStore = defineStore('lang', () => {

  const langActif = ref(localStorage.getItem('lang') || 'fr')
  const langOpen  = ref(false)

  const langues = [
    { code: 'fr', label: 'Français', flag: '🇫🇷' },
    { code: 'en', label: 'English',  flag: '🇬🇧' },
    { code: 'mg', label: 'Malagasy', flag: '🇲🇬' },
  ]

  function setLang(code) {
    langActif.value = code
    localStorage.setItem('lang', code)
    langOpen.value  = false
  }

  // ── Toutes les traductions centralisées ─────────────────────────────────────
  const i18n = {
    fr: {
      // Nav / Header
      accueil:        '🏠 ACCUEIL',
      formations:     '📘 NOS FORMATIONS',
      niveaux:        '🎯 LES NIVEAUX',
      contact:        '📞 CONTACT',
      apprenant:      '🎓 ESPACE APPRENANT',
      login:          '🔐 Connexion',
      sinscrire:      "📝 S'inscrire",
      // Hero
      badge:          '🏆 Programme officiel CNFPPSH',
      heroTitle1:     'Obtenez votre',
      heroAccent:     'Permis TIC',
      heroDesc:       "Formation professionnelle en informatique reconnue par l'État — Niveaux A, B et C — Ampandrianomby, Antananarivo",
      // Stats
      statFormations: 'Formations',
      statApprenants: 'Apprenants',
      statFormateurs: 'Formateurs',
      statReussite:   'Taux de réussite',
      // Formations
      nosFormations:  'Nos Formations',
      choixNiveau:    'Choisissez votre niveau et commencez votre parcours numérique',
      chargement:     'Chargement des formations…',
      places:         'places',
      sinscrireBtn:   "S'inscrire →",
      aucuneFormation:'Aucune formation disponible pour ce niveau actuellement.',
      descDefault:    'Formation professionnelle en informatique.',
      niveauA:        'Niveau A',
      niveauB:        'Niveau B',
      niveauC:        'Niveau C',
      niveau:         'Niveau',
      // Niveaux section
      les3niveaux:    'Les 3 Niveaux du Permis TIC',
      debutant:       'Débutant',
      intermediaire:  'Intermédiaire',
      avance:         'Avancé',
      // CTA
      ctaTitre:       'Prêt à commencer votre formation ?',
      ctaDesc:        'Rejoignez nos apprenants et obtenez votre certification officielle.',
      ctaBtn:         "S'inscrire maintenant",
      // Footer
      droits:         'Tous droits réservés',
      visiterSite:    'Visiter le site public',
      // Login
      connexion:      'Connexion',
      pasDeCompte:    'Pas encore de compte ?',
      inscrivezVous:  'Inscrivez-vous',
      emailLabel:     'Email',
      mdpLabel:       'Mot de passe',
      mdpOublie:      'Mot de passe oublié ?',
      seConnecter:    'Se connecter',
      continuerGoogle:'Continuer avec Google',
      erreurLogin:    'Email ou mot de passe incorrect.',
      erreurValidation:"Votre compte est en attente de validation par l'administrateur.",
      bienvenue:      'Bienvenue',
      seConnecterSub: 'Se connecter',
      // Register
      creerCompte:    'Créer votre compte apprenant',
      prenomLabel:    'Prénom',
      nomLabel:       'Nom',
      telephoneLabel: 'Téléphone',
      passwordLabel:  'Mot de passe',
      confirmerMdp:   'Confirmer le mot de passe',
      choisirFormation:'Choisir une formation',
      nomComplet:     'Nom complet',
      formation:      'Formation',
      etape1:         'Vos informations',
      etape2:         'Votre formation',
      etape3:         'Confirmation',
      suivant:        'Suivant →',
      precedent:      '← Précédent',
      sinscrireGoogle:"S'inscrire avec Google",
      dejaInscrit:    'Déjà inscrit ?',
      successInscription:'🎉 Votre inscription a été envoyée ! Un administrateur va valider votre compte.',
      // Espace apprenant
      mesFormations:  'Mes Formations',
      mesLecons:      'Mes Leçons',
      mesNotes:       'Mes Notes',
      mesCertificats: 'Certificats',
      mesInfos:       'Mes Infos',
      deconnexion:    '🚪 Déconnexion',
      aucuneInscription:'Vous n\'êtes inscrit à aucune formation pour le moment.',
      certifDisponible:'Votre certificat sera disponible une fois votre formation terminée.',
      telecharger:    '📄 Télécharger mon certificat',
      enAttente:      'En attente de validation',
      confirme:       'Confirmé',
      rejete:         'Non retenu',
      progression:    'Progression',
      // Niveaux section — nouveaux
      commencerBtn:   'Commencer maintenant →',
      nos3niveaux:    'Nos 3 niveaux',
      nsTitre1:       'Apprenez des compétences',
      nsTitre2:       'numériques modernes',
      nsSub:          "Un parcours progressif conçu pour vous amener de débutant à expert",
      decouvrir:      'Découvrir →',
    },
    en: {
      accueil:        '🏠 HOME',
      formations:     '📘 OUR COURSES',
      niveaux:        '🎯 LEVELS',
      contact:        '📞 CONTACT',
      apprenant:      '🎓 LEARNER SPACE',
      login:          '🔐 Login',
      sinscrire:      '📝 Register',
      badge:          '🏆 Official CNFPPSH Programme',
      heroTitle1:     'Get your',
      heroAccent:     'TIC License',
      heroDesc:       'Professional IT training recognized by the State — Levels A, B and C — Ampandrianomby, Antananarivo',
      statFormations: 'Courses',
      statApprenants: 'Learners',
      statFormateurs: 'Trainers',
      statReussite:   'Success rate',
      nosFormations:  'Our Courses',
      choixNiveau:    'Choose your level and start your digital journey',
      chargement:     'Loading courses…',
      places:         'seats',
      sinscrireBtn:   'Register →',
      aucuneFormation:'No courses available for this level at the moment.',
      descDefault:    'Professional IT training.',
      niveauA:        'Level A',
      niveauB:        'Level B',
      niveauC:        'Level C',
      niveau:         'Level',
      les3niveaux:    'The 3 Levels of the TIC License',
      debutant:       'Beginner',
      intermediaire:  'Intermediate',
      avance:         'Advanced',
      ctaTitre:       'Ready to start your training?',
      ctaDesc:        'Join our learners and get your official certification.',
      ctaBtn:         'Register now',
      droits:         'All rights reserved',
      visiterSite:    'Visit the public site',
      connexion:      'Login',
      pasDeCompte:    'No account yet?',
      inscrivezVous:  'Sign up',
      emailLabel:     'Email',
      mdpLabel:       'Password',
      mdpOublie:      'Forgot password?',
      seConnecter:    'Sign in',
      continuerGoogle:'Continue with Google',
      erreurLogin:    'Incorrect email or password.',
      erreurValidation:'Your account is awaiting administrator validation.',
      bienvenue:      'Welcome',
      seConnecterSub: 'Sign in',
      creerCompte:    'Create your learner account',
      prenomLabel:    'First name',
      nomLabel:       'Last name',
      telephoneLabel: 'Phone',
      passwordLabel:  'Password',
      confirmerMdp:   'Confirm password',
      choisirFormation:'Choose a course',
      nomComplet:     'Full name',
      formation:      'Course',
      etape1:         'Your details',
      etape2:         'Your course',
      etape3:         'Confirmation',
      suivant:        'Next →',
      precedent:      '← Back',
      sinscrireGoogle:'Register with Google',
      dejaInscrit:    'Already registered?',
      successInscription:'🎉 Your registration has been sent! An administrator will validate your account.',
      mesFormations:  'My Courses',
      mesLecons:      'My Lessons',
      mesNotes:       'My Grades',
      mesCertificats: 'Certificates',
      mesInfos:       'My Info',
      deconnexion:    '🚪 Sign out',
      aucuneInscription:'You are not enrolled in any course yet.',
      certifDisponible:'Your certificate will be available once your training is complete.',
      telecharger:    '📄 Download my certificate',
      enAttente:      'Awaiting validation',
      confirme:       'Confirmed',
      rejete:         'Not selected',
      progression:    'Progress',
      // Niveaux section — nouveaux
      commencerBtn:   'Start now →',
      nos3niveaux:    'Our 3 levels',
      nsTitre1:       'Learn modern',
      nsTitre2:       'digital skills',
      nsSub:          'A progressive path designed to take you from beginner to expert',
      decouvrir:      'Discover →',
    },
    mg: {
      accueil:        '🏠 FANDRAISANA',
      formations:     '📘 FIOFANANA',
      niveaux:        '🎯 AMBARATONGA',
      contact:        '📞 FIFANDRAISANA',
      apprenant:      '🎓 HABAKA MPIANATRA',
      login:          '🔐 Hiditra',
      sinscrire:      '📝 Misoratra',
      badge:          "🏆 Programa ofisialin'ny CNFPPSH",
      heroTitle1:     'Mahazo ny',
      heroAccent:     'Permis TIC',
      heroDesc:       "Fiofanana amin'ny informatika voamarina ara-panjakana — Ambaratonga A, B ary C — Ampandrianomby, Antananarivo",
      statFormations: 'Fiofanana',
      statApprenants: 'Mpianatra',
      statFormateurs: 'Mpampianatra',
      statReussite:   "Tahan'ny fahombiazana",
      nosFormations:  'Ny Fiofanana',
      choixNiveau:    "Misafidiana ny ambaratongánao ary atombohy ny dianao amin'ny teknolojia",
      chargement:     'Ampidirina ny fiofanana…',
      places:         'toerana',
      sinscrireBtn:   'Misoratra →',
      aucuneFormation:"Tsy misy fiofanana amin'ity ambaratonga ity ankehitriny.",
      descDefault:    "Fiofanana amin'ny informatika.",
      niveauA:        'Ambaratonga A',
      niveauB:        'Ambaratonga B',
      niveauC:        'Ambaratonga C',
      niveau:         'Ambaratonga',
      les3niveaux:    "Ny Ambaratonga 3 amin'ny Permis TIC",
      debutant:       'Mpianatra',
      intermediaire:  'Antonony',
      avance:         'Avo lenta',
      ctaTitre:       'Vonona hanomboka ny fiofananao?',
      ctaDesc:        "Hidira amin'ny mpianatra ary mahazo ny fanamarinana ofisialy.",
      ctaBtn:         'Misoratra ankehitriny',
      droits:         'Zo rehetra voatokana',
      visiterSite:    'Tsidio ny tranonkala',
      connexion:      'Hiditra',
      pasDeCompte:    'Tsy manana kaonty?',
      inscrivezVous:  'Misoratra',
      emailLabel:     'Imailaka',
      mdpLabel:       'Teny miafina',
      mdpOublie:      'Adino ny teny miafina?',
      seConnecter:    'Hiditra',
      continuerGoogle:'Mitohy amin\'ny Google',
      erreurLogin:    'Imailaka na teny miafina diso.',
      erreurValidation:'Ny kaontinao dia miandry fanamarinana ny mpitantana.',
      bienvenue:      'Tongasoa',
      seConnecterSub: 'Hiditra',
      creerCompte:    'Hamorona kaonty mpianatra',
      prenomLabel:    'Anarana voalohany',
      nomLabel:       'Fianakaviana',
      telephoneLabel: 'Finday',
      passwordLabel:  'Teny miafina',
      confirmerMdp:   'Avereno ny teny miafina',
      choisirFormation:'Misafidiana fiofanana',
      nomComplet:     'Anarana feno',
      formation:      'Fiofanana',
      etape1:         'Ny mombamombanao',
      etape2:         'Ny fiofananao',
      etape3:         'Fanamarinana',
      suivant:        'Manaraka →',
      precedent:      '← Hiverina',
      sinscrireGoogle:'Misoratra amin\'ny Google',
      dejaInscrit:    'Efa misoratra?',
      successInscription:"🎉 Voaray ny fandraharahana! Hanamarina ny kaontinao ny mpitantana.",
      mesFormations:  'Ny Fiofanako',
      mesLecons:      'Ny Lesoko',
      mesNotes:       'Ny Notako',
      mesCertificats: 'Sertifika',
      mesInfos:       'Ny Mombamombako',
      deconnexion:    '🚪 Mivoaka',
      aucuneInscription:'Tsy voasoratra amin\'ny fiofanana ianao ankehitriny.',
      certifDisponible:'Hisitraka ny sertifikà rehefa vita ny fiofanana.',
      telecharger:    '📄 Alao ny sertifikàko',
      enAttente:      'Miandry fanamarinana',
      confirme:       'Voamarika',
      rejete:         'Tsy noraisina',
      progression:    'Fandrosoan\'ny',
      // Niveaux section — nouveaux
      commencerBtn:   'Atombohy ankehitriny →',
      nos3niveaux:    'Ny Ambaratonga 3',
      nsTitre1:       'Mianara fahaizana',
      nsTitre2:       'teknolojia maoderina',
      nsSub:          "Lalana fandrosoana natao hampandrosoana anao hatramin'ny mpianatra ka hatramin'ny manam-pahaizana",
      decouvrir:      'Hijerena →',
    },
  }

  const t = computed(() => i18n[langActif.value] || i18n.fr)

  return { langActif, langOpen, langues, setLang, t, i18n }
})